rhai:
  scripts: rhai
  main: main.rhai
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
headers:
  all:
    request:
      - insert:
          name: ENTITLEMENTS_BYPASS
          from_context: ENTITLEMENTS_BYPASS
